apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: employee-system
data:
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: employee
  DB_USER: root
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: employee-system
type: Opaque
stringData:
  DB_PASSWORD: YOUR_PASSWORD_HERE